[tool.poetry]
name = "nasa-exoplanet"
version = "0.1.0"
description = ""
authors = ["Sanzhar Ilichbekov"]

[tool.poetry.dependencies]
python = "^3.12"
Flask = "3.0.3"
Flask-Cors = "4.0.1"
gunicorn = "22.0.0"
numpy = "1.26.4"
